# Generated by Django 3.2.5 on 2022-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
