# Generated by Django 3.2.5 on 2022-02-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_posts_icon_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='unliked',
        ),
    ]
