# Generated by Django 3.2.5 on 2022-02-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_posts_unliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='icon_clicked',
        ),
        migrations.AddField(
            model_name='user',
            name='icon_clicked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
